name: Jv
channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- matplotlib
- numpy
- pandas
- pip
- scikit-image
- scikit-learn=1.2
- spyder-kernels=2.4
- tqdm
- pip:
  - open3d==0.17
  - pyarrow
  - openpyxl