name: Jv
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- matplotlib
- numpy
- pandas
- pip
- scikit-image
- scikit-learn=1.5
- spyder-kernels=3.0
- tqdm
- trimesh=4.6.0
- pip:
  - pyarrow
  - openpyxl