name: Jv
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- matplotlib
- numpy
- pandas
- pip
- scikit-image
- scikit-learn=1.5
- spyder-kernels=2.5
- tqdm
- pip:
  - open3d==0.18
  - pyarrow
  - openpyxl